# Generated by Django 5.0.7 on 2024-11-01 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Timer', '0012_event_pomodorotimer_reminder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PomodoroTimer',
        ),
    ]
